spring:
  application:
    name: fraud-detection-service

  # Database Configuration
  datasource:
    url: jdbc:h2:mem:frauddb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # AWS Configuration
  cloud:
    aws:
      region:
        static: us-east-1
        auto: false
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      sqs:
        endpoint: ${AWS_SQS_ENDPOINT:https://sqs.us-east-1.amazonaws.com}
      cloudwatch:
        enabled: true
        endpoint: ${AWS_CLOUDWATCH_ENDPOINT:https://logs.us-east-1.amazonaws.com}
        namespace: ${spring.application.name}
        log-group: /aws/fraud-detection
        retention-in-days: 30
        metrics:
          enabled: true
          batch-size: 100

# Fraud Detection Configuration
fraud:
  detection:
    amount:
      threshold: 1000
    suspicious:
      transactions:
        threshold: 3

# AWS SQS Configuration
aws:
  sqs:
    queue:
      transactions: fraud-detection-queue

# Logging Configuration
logging:
  level:
    com.example.frauddetection: INFO
    org.springframework.kafka: INFO